---
title: "MS_sandbox"
output: html_document
date: '2022-10-12'
---

library(ggplot2)
library(ggrepel)

# import gtex data

temp <- tempfile()
download.file("https://storage.googleapis.com/gtex_analysis_v9/long_read_data/quantification_gencode.tpm.txt.gz",temp)
gtex <- read.table(temp, skip=0, header = TRUE, sep = "\t")
gtex_rowinfo <- data.frame(Name=gtex$Name, Description=gtex$Description)
rownames(gtex) <- gtex$transcript

---

# boxplot

# boxplot that compares the distribution of transcript expression of 2 gene samples

# with outliers
boxplot(gtex$GTEX.1192X.0011.R10a.SM.4RXXZ, gtex$GTEX.11H98.0011.R11b.SM.4SFLZ,
main = "Quantification of transcripts in two \n gene samples (with outliers)",
xlab = "Sample ID",
ylab = "Quantification in TPM",
outline = TRUE
)

legend(x = "topright", legend = c("GTEX.1192X.0011.R10a.SM.4RXXZ","GTEX.11H98.0011.R11b.SM.4SFLZ"), fill = c("blue","red"))


# without outliers
boxplot(gtex$GTEX.1192X.0011.R10a.SM.4RXXZ, gtex$GTEX.11H98.0011.R11b.SM.4SFLZ,
main = "Quantification of transcripts in two \n samples without outliers",
xlab = "Sample ID",
ylab = "Quantification in TPM",
outline = FALSE
)


---

# volcano plot



---

# scatterplot

plot(x = gtex$GTEX.1192X.0011.R10a.SM.4RXXZ,
y = gtex$GTEX.11H98.0011.R11b.SM.4SFLZ,
main = "Comparison of expression of each \n transcript for 2 gene samples",
xlab = "GTEX.1192X.0011.R10a.SM.4RXXZ",
ylab = "GTEX.11H98.0011.R11b.SM.4SFLZ",
xlim = c(0,3000), ylim = c(0,3000), cex = 0.5
)

# regression line
abline(lm(GTEX.11H98.0011.R11b.SM.4SFLZ~GTEX.1192X.0011.R10a.SM.4RXXZ, 
data=gtex), col='red')


---

# histogram
# for colour scheme, val typically prefers greyscale. or, this red/blue combo she seems fine with too

hist(gtex$GTEX.11H98.0011.R11b.SM.4SFLZ, breaks=100,
main = "Frequency of quantifications in sample \n GTEX.11H98.0011.R11b.SM.4SFLZ", 
xlab = "Quantification in TPM", ylab = "Frequency",
xlim = c(0,2000))

order(gtex$GTEX.11H98.0011.R11b.SM.4SFLZ)



---

# heatmap



---